In [ ]:
import numpy as np
import pandas as pd

class MLP():
    def __init__(self, learning_rate):
        self.learning_rate = learning_rate
        # 4 inputs -> 3 neurons
        self.W1 = np.zeros((3, 4))
        self.b1 = np.zeros((3, 1))

        # 3 inputs -> 2 neurons
        self.W2 = np.zeros((2,3))
        self.b2 = np.zeros((2,1))

         # 2 inputs -> 1 neuron
        self.W3 = np.zeros((1,2))
        self.b3 = np.zeros((1,1))

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def forward(self, x):
        # Input -> Hidden Layer 1
        z1 = self.W1 @ x + self.b1
        h1 = self.sigmoid(z1)

        # Hidden Layer 1 -> Hidden Layer 2
        z2 = self.W2 @ h1 + self.b2
        h2 = self.sigmoid(z2)

        # Hidden Layer 2 -> Output
        z3 = self.W3 @ h2 + self.b3
        output = self.sigmoid(z3)
        return output


In [ ]:
network = MLP()

df = pd.read_csv("student_placement_4_features.csv")

# np.random.seed(42)

# df["Attendance"] = np.random.randint(60, 101, size=len(df))
# df["Projects"] = np.random.randint(0, 5, size=len(df))

# # Make sure Placement is the last column
# df = df[["CGPA", "12th_Marks", "Attendance", "Projects", "Placement"]]

# df.to_csv("student_placement_4_features.csv", index=False)

print(df.head())

x = df.iloc[0, :-1].values.reshape(-1, 1)

# x = np.array([
#     [0.8],
#     [0.6],
#     [0.7],
#     [0.9]
# ])

prediction = network.forward(x)

print("Prediction:")
print(prediction)
# print(network.W1, network.W2)

   CGPA  12th_Marks  Attendance  Projects  Placement
0  8.20       51.25          98         1          0
1  6.38       61.16          88         0          0
2  8.68       83.83          74         4          1
3  9.46       54.35          67         2          0
4  7.11       51.49          80         3          0
Prediction:
[[0.5]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[0. 0. 0.]
 [0. 0. 0.]]
